# 1. File I/O Configuration
file_io:
  input_path: "data/input"     # Where the application reads files from
  output_path: "data/output"   # Where the application saves the results

# 2. Logging Configuration
logging:
  enabled: true                # Set to false to disable logging
  level: "INFO"                # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(levelname)s - %(message)s"
  handlers:
    - type: "stream"
    - type: "file"
      filename: "logs/app.log"
      mode: "a"

# 3. Reading Methods Configuration
reader:
  method: "markitdown" # available: markitdown, docling, pdfplumber

# 4. Splitting Methods Configuration
splitter:
  method: "recursive"

  methods:
    word:
      num_words: 100  # Number of words in each chunk

    sentence:
      num_sentences: 5  # Number of sentences in each chunk

    paragraph:
      num_paragraphs: 3  # Number of paragraphs in each chunk

    # semantic:
    #   language_model: "bert-base-uncased"  # For semantic similarity
    #   overlap: 0.2                         # Overlap ratio between chunks

    fixed:
      size: 100  # Number of characters per chunk

    # paged:
    #   num_pages: 1  # Number of pages in each chunk
    #   overlap: 0.1  # Overlap (in pages) between chunks

    recursive:
      size: 2048     # Characters per chunk
      overlap: 128   # Overlapping characters

    # row-column:
    #   num_columns: 2
    #   column_names: ["Column1", "Column2"]
    #   num_rows: 5
    #   row_names: ["Row1", "Row2"]

    # schema-based:
    #   num_registers: 50  # Number of registers (or rows) per chunk
    #   overlap: 5         # Overlapping registers

    # auto:
    #   fallback_method: "paragraph"
    #   chunk_size: 500
    #   overlap: 100

# 5. OCR configuration
ocr:
  method: "none"  # Options: azure, openai, none
  # include_image_blobs: false
  # include_json_structure: false