[project]
name = "splitter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "markdown>=3.7",
    "markitdown>=0.0.1a5",
    "pandas>=2.2.3",
    "pytesseract>=0.3.13",
    "pytest>=8.3.5",
    "pyyaml>=6.0.2",
]
