[project]
name = "splitter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "docx>=0.2.4",
    "markdown>=3.7",
    "pandas>=2.2.3",
    "pillow>=11.1.0",
    "pypdf2>=3.0.1",
    "pytesseract>=0.3.13",
    "pytest>=8.3.5",
    "pyyaml>=6.0.2",
]
